---

# ----------------------------------
# Users
# ----------------------------------
ssh_user: vagrant
www_user: vagrant

# ----------------------------------
# Paths
# ----------------------------------
app_root: /vagrant
